### ISSUE TITLE
Min/max width/height auto layout constraints don't seem to work

### ISSUE THREAD

**Issue by iamralpht** [google/automotive-design-compose#1545]
I noticed that setting min/max constraints on an auto layout node seems to be ignored. It would be good to support this fully; I think that Taffy supports min/max, so we should be able to hook this up.

**Comment by iamralpht** [comment]
Lower priority than #1556 for sure

**Comment by yiqunw700** [comment]
Having issue with measuring with node https://www.figma.com/design/ArHVZAQIsKf2B9mATnVvLX/AutoLayout?node-id=1-8&node-type=frame&t=xrMeVa2Wr6yzULtn-0 where the outer frame has max size set and the inner frame has min size set.
Also notice that the flex direction has an impact on the result:
Vertical layout ->height is measured only with paddings added up
Horizontal layout -> width is measured only with paddings added up

This only happens when the outer container is placed inside a non-auto layout container or an auto-layout container with a different flex direction. Works if it is placed inside an auto-layout container with the same flex direction.

This is similar to what have been reported to taffy: https://github.com/DioxusLabs/taffy/issues/591
