### ISSUE TITLE
Support FILL sizing mode for autolayout frames

### ISSUE THREAD

**Issue by rylin8** [google/automotive-design-compose#401]
Currently the FILL sizing mode is treated as FIXED, matching the Figma width or height. By setting the style attribute to Auto, the container expands to fit its children no matter how large its parent is. Perhaps need to ignore children when container set to FILL so it doesn’t expand past size of children, or use a custom measure function passed in.

**Comment by rylin8** [comment]
I see a couple ways of doing this but they aren't straightforward.
1. When we encounter an autolayout frame with a width or height set to FILL container (let's call this "auto-fill"), automatically create another frame (let's call this "auto-parent") that serves as the parent of auto-fill. auto-parent gets all the same properties as auto-fill, and its justify-self and/or align-self properties are set to 1, and its width and/or height properties are set to Auto. auto-parent has an absolute layout with one child, auto-fill, at 0, 0. auto-fill.
2. Trick the layout system into laying out the autolayout frame with FILL to compute layout with no children, then add the children back in.

I'm leaning toward #1. @iamralpht does this seem feasible, or do you have any other ideas?

**Comment by rylin8** [comment]
Figured out that the key to sizing a FILL node correctly is setting flex_grow to 1 and flex_basis to Dimension::Points(0). This allows the node to start out at 0 pixels and grow to fill its parent.

**Comment by Methodician** [comment]
Here is a sample file with a generic tab component and variants
Figma Link: [Fill Fail Example](https://www.figma.com/design/NQo9P4HcI5FupUMJtm4kRx/Fill-Fail-Example?node-id=0-1&t=qpBl4m0sTfEHim5j-1)
.Fig Zip: [Fill Fail Example.fig.zip](https://github.com/user-attachments/files/21129190/Fill.Fail.Example.fig.zip)

Focus on the top tab ("selected").

Here, I am achieving the desired results with the text node and its parents using "Hug contents" for width and range of height settings as it bubbles up. The underline is set to "Fill container" for the width. Because its parent width grows with a longer label string, the underline width grows with it to fill the container.

This works as expected in Figma, but not in Android. The underline width remains fixed in the emulator.

**Comment by Methodician** [comment]
Just bumping this and wondering if anyone has looked at it?
