### ISSUE TITLE
Support pinning to/fetching a particular version of a design from Figma

### ISSUE THREAD

**Issue by iamralpht** [google/automotive-design-compose#718]
Request to better support production workflows: https://buganizer.corp.google.com/issues/317081065

Currently you can fetch a particular branch or document, but can't specify a non-top version. This could be important for some production workflows, where assets need to be protected, or re-created from an old version of a design.

**Comment by rylin8** [comment]
The [GET FILE API](https://www.figma.com/developers/api#get-files-endpoint) has a version field we could use to achieve this. The code to construct this URL is at 
https://github.com/google/automotive-design-compose/blob/f173624281ecfdc866e106bc9ac41d636706ab21/crates/figma_import/src/document.rs#L160.

We would need to add a version parameter somewhere, perhaps in the `@DesignDoc` annotation [defined here](https://github.com/google/automotive-design-compose/blob/main/annotation/src/main/java/com/android/designcompose/annotation/Builder.kt) and [parse it out](https://github.com/google/automotive-design-compose/blob/f173624281ecfdc866e106bc9ac41d636706ab21/codegen/src/main/kotlin/com/android/designcompose/codegen/BuilderProcessor.kt#L206), then generate some code so that the version, if specified, gets sent in the fetch request for the document.
