### ISSUE TITLE
Missing fonts in Tutorial file when opened by a user who is not in the Figma Google Org.

### ISSUE THREAD

**Issue by timothyfroehlich** [google/automotive-design-compose#77]
Repro:
- Make a copy of https://www.figma.com/community/file/1228110686419863535/Tutorial-for-Automotive-Design-for-Compose with an OTA or personal account.
- Open it, go to `Text 1 - Live`
- Double-click on the green `00:00` text a few times
- Result is below:

![image](https://github.com/google/automotive-design-compose/assets/5819722/6e250a11-6385-444a-820e-680ae7d3a206)

**Comment by timothyfroehlich** [comment]
Cannot adjust text formatting in `Text 2 - Live` due to this.

**Comment by timothyfroehlich** [comment]
Can't adjust text formatting in `Auto content 7 - Live` due to this.

**Comment by iamralpht** [comment]
Hm, we were trying to use Google design language in the tutorial, but Google Sans and friends aren't (and won't be) publicly available. I think we might need to switch back to Noto/Roboto. cc @miriamvu and aubrey.

I'm moving this out of 0.19 because it'll take a while to fix, and someone should be able to make it thru by changing the font (although that's not ideal at all).

**Comment by iamralpht** [comment]
@timothyfroehlich did we publish an updated tutorial file? This is the last open ticket in 0.20.

**Comment by timothyfroehlich** [comment]
We did. I think this can be closed.
