### ISSUE TITLE
Figma animations not implemented yet?

### ISSUE THREAD

**Issue by MarcFerrerMargarit** [google/automotive-design-compose#825]
I was doing the prototype on figma and adding some animations fade in and fade out and I saw that on the android emulator those animations didn't work. 

I read that this type of animations is still not supported, it is planned to add this feature in a short/long term?

Is any way to do that type of animations on source code with composables?

**Comment by timothyfroehlich** [comment]
There's work being done on Animations but I can't say when it'll be ready, unfortunately. It's on our roadmap for sure. 

Compose animations can be applied manually, to some extent, but I really can't help much more than that.

**Comment by MarcFerrerMargarit** [comment]
Okey! Thank you very much!

**Comment by iamralpht** [comment]
@MarcFerrerMargarit a very very limited initial implementation of animations if you enable the "squoosh" implementation 
(this regresses other features like content replacement and lists & grids, which is why it's currently disabled). https://github.com/google/automotive-design-compose/blob/3d8f2e9f5e39ff32476e6d3ee3e576e9e612b339/designcompose/src/main/java/com/android/designcompose/DesignView.kt#L971

**Comment by rylin8** [comment]
This is working when squoosh is turned on, which will be by default soon.
